config/routes.rb
Rails.application.routes.draw do


  resources :student_profiles
  resources :skills
  resources :jobs
  resources :job_types
  resources :companies do
    member do
      post :approve
    end
  end
  root 'home#index'

  devise_for :users
  get 'admin', to: 'pages#admin'
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'dashboard', to: 'pages#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  belongs_to :job_type
  has_many :job_skills
  has_many :skills, through: :job_skills

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    [address, city, state, country].compact.join(', ')
  end

  include Workflow
  workflow do
    state :new do
      event :submit, :transitions_to => :awaiting_approval
    end
    state :awaiting_approval do
      event :accept, :transitions_to => :live
      event :reject, :transitions_to => :rejected
    end
    state :live do
      event :hire, :transitions_to => :filled
      event :cancel, :transition_to => :cancelled
      event :archive, :transition_to => :archived
      event :expire, :transition_to => :expired
    end
    state :filled
    state :rejected
    state :cancelled
    state :archived
  end
end

app/models/job_type.rb
class JobType < ApplicationRecord
  has_many :jobs
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show, :index]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.company = current_user.company
    @job.closing_date = Date.today + 30.days

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:description, :title, :remote, :address, :city, :state, :country, :job_type_id, :experience_level, :hourly_rate)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for(@job) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, label: 'Job title' %>
    <%= f.input :description, label: 'Job description' %>
    <%= f.input :hourly_rate, label: 'Hourly rate offered in AUD', collection: [30, 40, 50, 60, 70, 80, 90, 100] %>
    <%= f.association :job_type, as: :radio_buttons %>
    <%= f.input :remote, label: 'Work can be done remotely?' %>
    <%= f.input :experience_level, collection: ['Junior', 'Intermediate', 'Senior'] %>
    <%= f.input :address, label: 'Address (Only city and country will be displayed)' %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :country, priority: ['Australia'], input_html: { class: 'my-select' } %>
  </div>

  <div class="form-actions">
    <%= f.submit 'Select required skills', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Title</th>
      <th>Remote</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Closing date</th>
      <th>Status</th>
      <th>Job type</th>
      <th>Experience level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.company %></td>
        <td><%= job.title %></td>
        <td><%= job.remote %></td>
        <td><%= job.address %></td>
        <td><%= job.city %></td>
        <td><%= job.state %></td>
        <td><%= job.country %></td>
        <td><%= job.closing_date %></td>
        <td><%= job.status %></td>
        <td><%= job.job_type %></td>
        <td><%= job.experience_level %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="card card-block">
      <h1 class="card-title">New Job</h1>
      <p class="lead">
        To be able to list a job, you need to first register your company and be approved by Coder Factory.
      </p>
    </div>

  </div>
  <div class="col-md-8">
    <div class="card card-block">
      <%= render 'form', job: @job %>
    </div>

  </div>

</div>


<%= link_to 'Cancel', dashboard_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Remote:</strong>
  <%= @job.remote %>
</p>

<p>
  <strong>Address:</strong>
  <%= @job.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @job.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @job.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @job.country %>
</p>

<p>
  <strong>Closing date:</strong>
  <%= @job.closing_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @job.status %>
</p>

<p>
  <strong>Job type:</strong>
  <%= @job.job_type %>
</p>

<p>
  <strong>Experience level:</strong>
  <%= @job.experience_level %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>