config/routes.rb
Rails.application.routes.draw do


  resources :student_profiles
  resources :skills
  resources :jobs
  resources :job_types
  resources :companies do
    member do
      post :approve
    end
  end
  root 'home#index'

  devise_for :users
  get 'admin', to: 'pages#admin'
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'dashboard', to: 'pages#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :jobs, dependent: :destroy

  scope :alphabetical, -> { order(name: :asc) }

  def approve
    update_attributes(approved: true)
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  belongs_to :job_type
  has_many :job_skills
  has_many :skills, through: :job_skills

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    [address, city, state, country].compact.join(', ')
  end

  include Workflow
  workflow do
    state :new do
      event :submit, :transitions_to => :awaiting_approval
    end
    state :awaiting_approval do
      event :accept, :transitions_to => :live
      event :reject, :transitions_to => :rejected
    end
    state :live do
      event :hire, :transitions_to => :filled
      event :cancel, :transition_to => :cancelled
      event :archive, :transition_to => :archived
      event :expire, :transition_to => :expired
    end
    state :filled
    state :rejected
    state :cancelled
    state :archived
  end
end

app/models/job_skill.rb
class JobSkill < ApplicationRecord
  belongs_to :job
  belongs_to :skill
end

app/models/job_type.rb
class JobType < ApplicationRecord
  has_many :jobs
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :job_skills
  has_many :jobs, through: :job_skills
  has_many :student_skills
  has_many :student_profiles, through: :student_skills

  scope :alphabetical, -> { order(name: :asc) }
end

app/models/student_profile.rb
class StudentProfile < ApplicationRecord
  belongs_to :user
  has_many :student_skills
  has_many :skills, through: :student_skills
end

app/models/student_skill.rb
class StudentSkill < ApplicationRecord
  belongs_to :student_profile
  belongs_to :skill
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_one :company
  has_one :student_profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show, :index]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.company = current_user.company
    @job.closing_date = Date.today + 30.days

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:description, :title, :remote, :address, :city, :state, :country, :job_type_id, :experience_level, :hourly_rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_types_helper.rb
module JobTypesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-faded navbar-fixed-top">
  <div class="container">
  <a class="navbar-brand" href="/">Coder Factory Job Board</a>
  <ul class="nav navbar-nav pull-xs-right">
    <% if user_signed_in? %>
      <% if current_user.has_role? :company %>
        <li class="nav-item"><%= link_to icon('dashboard') + ' Dashboard', dashboard_path, class: 'nav-link' %></li>
      <% end %>
    <% else %>
      <li class="nav-item">
        <a class="nav-link btn btn-success-outline" href="/companies/new">Register your company</a>
      </li>
    <% end %>
    <li class="nav-item">
      <a class="nav-link" href="/jobs"><%= icon('briefcase') %> All jobs</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/companies"><%= icon('building') %> Companies</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/about"><%= icon('question-circle') %> About</a>
    </li>
    <% if user_signed_in? %>
      <li class="nav-item"><%= link_to icon('sign-out') + 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
      <% if current_user.has_role? :admin %>
        <li class="nav-item"><%= link_to 'Admin', admin_path, class: 'nav-link' %></li>
      <% end %>

    <% else %>
      <li class="nav-item"><%= link_to 'Sign in / Register', new_user_session_path, class: 'nav-link' %></li>
    <% end %>
  </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/_companies.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Company Name</th>
      <th>Contact name</th>
      <th class="text-center">Approved</th>
      <th class="text-center">
        Active Jobs
      </th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, company %> <small><%= link_to icon('external-link'), company.website, target: '_blank' %></small></td>
        <td><%= company.contact_name %></td>
        <td class="text-center">
          <% if company.approved %>
            <%= icon('check-circle') %>
          <% else %>
            <%= button_to 'Approve', approve_company_path(company), class: 'btn btn-success btn-sm', data: { confirm: 'Are you sure?'} %>
          <% end %>
        </td>
        <td class="text-center">
          ?
        </td>
        <td class="text-center"><%= link_to icon('trash'), company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pages/_new_companies.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Company Name</th>
      <th>Contact name</th>
      <th></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @new_companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, company.website, target: '_blank' %></td>
        <td><%= company.contact_name %></td>
        <td><%= button_to 'Approve', approve_company_path(company), class: 'btn btn-success btn-sm', data: { confirm: 'Are you sure?'} %></td>
        <td><%= link_to 'Details', company, class: 'btn btn-warning btn-sm' %></td>
        <td><%= link_to icon('trash'), company, class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pages/_skills.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>
        Icon
      </th>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td>
          <%= image_tag skill.icon, width: '30px' %>
        </td>
        <td><%= link_to skill.name, skill %></td>
        <td><%= link_to icon('pencil'), edit_skill_path(skill) %></td>
        <td><%= link_to icon('trash'), skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/admin.html.erb
<h1>Admin</h1>
<% if notice %>
<p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<div class="row">
  <div class="col-md-4">
    <div class="card card-block">
      <ul class="nav nav-pills nav-stacked">
        <li class="nav-item">
          <%= link_to admin_path(show: 'companies'), class: 'nav-link' do %>
            Companies <span class="label label-default"><%= @companies.count %></span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_path(show: 'active-jobs'), class: 'nav-link' do %>
            Active Jobs <span class="label label-default"><%= @active_jobs.count %></span>
          <% end %>
        </li>
        <hr>
        <li class="nav-item">
          <%= link_to admin_path(show: 'skills'), class: 'nav-link' do %>
            Skills <span class="label label-default"><%= @skills.count %></span>
          <% end %>
        </li>
      </ul>
    </div>

  </div>
  <div class="col-md-8">
    <% if @new_companies.any? %>
      <div class="card card-block">
        <h2 class="card-title">New company registrations</h2>
        <%= render 'new_companies' %>
      </div>
    <% end %>
    <% if params[:show] == 'companies' %>
      <div class="card card-block">
        <h2 class="card-title">All companies</h2>
        <%= render 'companies' %>
      </div>
    <% end %>
    <% if params[:show] == 'skills' %>
      <div class="card card-block">
        <h2 class="card-title">All skills</h2>
        <%= render 'skills' %>
      </div>
    <% end %>

  </div>

</div>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>
<% if notice %>
<p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<div class="row">
  <div class="col-md-4">
    <div class="card card-block">
      <%= render 'companies/form' %>
    </div>
  </div>
  <div class="col-md-8">
    <%= link_to icon('plus-circle') + ' Add a job', new_job_path, class: 'btn btn-success' %>
    <% if @jobs.any? %>
      <div class="card card-block">
        <h2 class="card-title">My listed jobs</h2>
        <%= render 'skills' %>
      </div>
    <% end %>

  </div>

</div>